// Flutter imports:
import 'package:flutter/material.dart';

class Cell {
  int x;
  int y;
  String value;
  bool shortest;
  int distance;
  Cell? parent;
  bool visited;

  Cell({
    required this.x,
    required this.y,
    required this.value,
    this.shortest = false,
    this.visited = false,
    this.distance = 0,
    this.parent,
  });

  String getText() {
    if (value == 'S') {
      return 'S';
    } else if (value == 'G') {
      return 'G';
    }
    return distance == 0 ? '' : distance.toString();
  }

  Color getColor() {
    if (shortest) {
      return Colors.red;
    }
    if (visited) {
      return Colors.blue;
    } else if (value == '#') {
      return Colors.black;
    }
    return Colors.white;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['x'] = x;
    data['y'] = y;
    data['distance'] = distance;
    data['shortest'] = shortest;
    data['visited'] = visited;
    data['value'] = value;
    data['parent'] = parent?.toJson();
    return data;
  }
}

List<List<Cell>> getMaze() {
  return [
    [
      Cell(x: 0, y: 0, value: '#'),
      Cell(x: 0, y: 1, value: '#'),
      Cell(x: 0, y: 2, value: '#'),
      Cell(x: 0, y: 3, value: '#'),
      Cell(x: 0, y: 4, value: '#'),
      Cell(x: 0, y: 5, value: '#'),
      Cell(x: 0, y: 6, value: '#'),
      Cell(x: 0, y: 7, value: '#'),
      Cell(x: 0, y: 8, value: '#'),
      Cell(x: 0, y: 9, value: '#'),
      Cell(x: 0, y: 10, value: '#'),
      Cell(x: 0, y: 11, value: '#'),
      Cell(x: 0, y: 12, value: '#'),
      Cell(x: 0, y: 13, value: '#'),
      Cell(x: 0, y: 14, value: '#'),
      Cell(x: 0, y: 15, value: '#'),
      Cell(x: 0, y: 16, value: '#'),
      Cell(x: 0, y: 17, value: '#'),
      Cell(x: 0, y: 18, value: '#'),
      Cell(x: 0, y: 19, value: '#'),
      Cell(x: 0, y: 20, value: '#'),
    ],
    [
      Cell(x: 1, y: 0, value: '#'),
      Cell(x: 1, y: 1, value: 'S', distance: 0),
      Cell(x: 1, y: 2, value: '#'),
      Cell(x: 1, y: 3, value: ''),
      Cell(x: 1, y: 4, value: ''),
      Cell(x: 1, y: 5, value: ''),
      Cell(x: 1, y: 6, value: '#'),
      Cell(x: 1, y: 7, value: ''),
      Cell(x: 1, y: 8, value: ''),
      Cell(x: 1, y: 9, value: ''),
      Cell(x: 1, y: 10, value: '#'),
      Cell(x: 1, y: 11, value: ''),
      Cell(x: 1, y: 12, value: '#'),
      Cell(x: 1, y: 13, value: ''),
      Cell(x: 1, y: 14, value: '#'),
      Cell(x: 1, y: 15, value: ''),
      Cell(x: 1, y: 16, value: ''),
      Cell(x: 1, y: 17, value: ''),
      Cell(x: 1, y: 18, value: '#'),
      Cell(x: 1, y: 19, value: ''),
      Cell(x: 1, y: 20, value: '#'),
    ],
    [
      Cell(x: 2, y: 0, value: '#'),
      Cell(x: 2, y: 1, value: ''),
      Cell(x: 2, y: 2, value: '#'),
      Cell(x: 2, y: 3, value: '#'),
      Cell(x: 2, y: 4, value: '#'),
      Cell(x: 2, y: 5, value: ''),
      Cell(x: 2, y: 6, value: '#'),
      Cell(x: 2, y: 7, value: '#'),
      Cell(x: 2, y: 8, value: '#'),
      Cell(x: 2, y: 9, value: ''),
      Cell(x: 2, y: 10, value: '#'),
      Cell(x: 2, y: 11, value: ''),
      Cell(x: 2, y: 12, value: '#'),
      Cell(x: 2, y: 13, value: ''),
      Cell(x: 2, y: 14, value: '#'),
      Cell(x: 2, y: 15, value: ''),
      Cell(x: 2, y: 16, value: '#'),
      Cell(x: 2, y: 17, value: ''),
      Cell(x: 2, y: 18, value: '#'),
      Cell(x: 2, y: 19, value: ''),
      Cell(x: 2, y: 20, value: '#'),
    ],
    [
      Cell(x: 3, y: 0, value: '#'),
      Cell(x: 3, y: 1, value: ''),
      Cell(x: 3, y: 2, value: '#'),
      Cell(x: 3, y: 3, value: ''),
      Cell(x: 3, y: 4, value: ''),
      Cell(x: 3, y: 5, value: ''),
      Cell(x: 3, y: 6, value: '#'),
      Cell(x: 3, y: 7, value: ''),
      Cell(x: 3, y: 8, value: ''),
      Cell(x: 3, y: 9, value: ''),
      Cell(x: 3, y: 10, value: '#'),
      Cell(x: 3, y: 11, value: ''),
      Cell(x: 3, y: 12, value: ''),
      Cell(x: 3, y: 13, value: ''),
      Cell(x: 3, y: 14, value: '#'),
      Cell(x: 3, y: 15, value: ''),
      Cell(x: 3, y: 16, value: '#'),
      Cell(x: 3, y: 17, value: ''),
      Cell(x: 3, y: 18, value: ''),
      Cell(x: 3, y: 19, value: ''),
      Cell(x: 3, y: 20, value: '#'),
    ],
    [
      Cell(x: 4, y: 0, value: '#'),
      Cell(x: 4, y: 1, value: ''),
      Cell(x: 4, y: 2, value: '#'),
      Cell(x: 4, y: 3, value: '#'),
      Cell(x: 4, y: 4, value: '#'),
      Cell(x: 4, y: 5, value: ''),
      Cell(x: 4, y: 6, value: '#'),
      Cell(x: 4, y: 7, value: '#'),
      Cell(x: 4, y: 8, value: '#'),
      Cell(x: 4, y: 9, value: ''),
      Cell(x: 4, y: 10, value: '#'),
      Cell(x: 4, y: 11, value: ''),
      Cell(x: 4, y: 12, value: '#'),
      Cell(x: 4, y: 13, value: '#'),
      Cell(x: 4, y: 14, value: '#'),
      Cell(x: 4, y: 15, value: '#'),
      Cell(x: 4, y: 16, value: '#'),
      Cell(x: 4, y: 17, value: ''),
      Cell(x: 4, y: 18, value: '#'),
      Cell(x: 4, y: 19, value: ''),
      Cell(x: 4, y: 20, value: '#'),
    ],
    [
      Cell(x: 5, y: 0, value: '#'),
      Cell(x: 5, y: 1, value: ''),
      Cell(x: 5, y: 2, value: ''),
      Cell(x: 5, y: 3, value: ''),
      Cell(x: 5, y: 4, value: ''),
      Cell(x: 5, y: 5, value: ''),
      Cell(x: 5, y: 6, value: '#'),
      Cell(x: 5, y: 7, value: ''),
      Cell(x: 5, y: 8, value: ''),
      Cell(x: 5, y: 9, value: ''),
      Cell(x: 5, y: 10, value: '#'),
      Cell(x: 5, y: 11, value: ''),
      Cell(x: 5, y: 12, value: ''),
      Cell(x: 5, y: 13, value: ''),
      Cell(x: 5, y: 14, value: ''),
      Cell(x: 5, y: 15, value: ''),
      Cell(x: 5, y: 16, value: ''),
      Cell(x: 5, y: 17, value: ''),
      Cell(x: 5, y: 18, value: '#'),
      Cell(x: 5, y: 19, value: ''),
      Cell(x: 5, y: 20, value: '#'),
    ],
    [
      Cell(x: 6, y: 0, value: '#'),
      Cell(x: 6, y: 1, value: ''),
      Cell(x: 6, y: 2, value: '#'),
      Cell(x: 6, y: 3, value: '#'),
      Cell(x: 6, y: 4, value: '#'),
      Cell(x: 6, y: 5, value: ''),
      Cell(x: 6, y: 6, value: '#'),
      Cell(x: 6, y: 7, value: ''),
      Cell(x: 6, y: 8, value: '#'),
      Cell(x: 6, y: 9, value: ''),
      Cell(x: 6, y: 10, value: '#'),
      Cell(x: 6, y: 11, value: ''),
      Cell(x: 6, y: 12, value: '#'),
      Cell(x: 6, y: 13, value: '#'),
      Cell(x: 6, y: 14, value: '#'),
      Cell(x: 6, y: 15, value: ''),
      Cell(x: 6, y: 16, value: '#'),
      Cell(x: 6, y: 17, value: ''),
      Cell(x: 6, y: 18, value: '#'),
      Cell(x: 6, y: 19, value: ''),
      Cell(x: 6, y: 20, value: '#'),
    ],
    [
      Cell(x: 7, y: 0, value: '#'),
      Cell(x: 7, y: 1, value: ''),
      Cell(x: 7, y: 2, value: '#'),
      Cell(x: 7, y: 3, value: ''),
      Cell(x: 7, y: 4, value: '#'),
      Cell(x: 7, y: 5, value: ''),
      Cell(x: 7, y: 6, value: '#'),
      Cell(x: 7, y: 7, value: ''),
      Cell(x: 7, y: 8, value: '#'),
      Cell(x: 7, y: 9, value: ''),
      Cell(x: 7, y: 10, value: ''),
      Cell(x: 7, y: 11, value: ''),
      Cell(x: 7, y: 12, value: '#'),
      Cell(x: 7, y: 13, value: ''),
      Cell(x: 7, y: 14, value: '#'),
      Cell(x: 7, y: 15, value: ''),
      Cell(x: 7, y: 16, value: '#'),
      Cell(x: 7, y: 17, value: ''),
      Cell(x: 7, y: 18, value: '#'),
      Cell(x: 7, y: 19, value: ''),
      Cell(x: 7, y: 20, value: '#'),
    ],
    [
      Cell(x: 8, y: 0, value: '#'),
      Cell(x: 8, y: 1, value: ''),
      Cell(x: 8, y: 2, value: '#'),
      Cell(x: 8, y: 3, value: ''),
      Cell(x: 8, y: 4, value: '#'),
      Cell(x: 8, y: 5, value: ''),
      Cell(x: 8, y: 6, value: '#'),
      Cell(x: 8, y: 7, value: '#'),
      Cell(x: 8, y: 8, value: '#'),
      Cell(x: 8, y: 9, value: ''),
      Cell(x: 8, y: 10, value: '#'),
      Cell(x: 8, y: 11, value: ''),
      Cell(x: 8, y: 12, value: '#'),
      Cell(x: 8, y: 13, value: ''),
      Cell(x: 8, y: 14, value: '#'),
      Cell(x: 8, y: 15, value: ''),
      Cell(x: 8, y: 16, value: '#'),
      Cell(x: 8, y: 17, value: '#'),
      Cell(x: 8, y: 18, value: '#'),
      Cell(x: 8, y: 19, value: '#'),
      Cell(x: 8, y: 20, value: '#'),
    ],
    [
      Cell(x: 9, y: 0, value: '#'),
      Cell(x: 9, y: 1, value: ''),
      Cell(x: 9, y: 2, value: '#'),
      Cell(x: 9, y: 3, value: ''),
      Cell(x: 9, y: 4, value: ''),
      Cell(x: 9, y: 5, value: ''),
      Cell(x: 9, y: 6, value: '#'),
      Cell(x: 9, y: 7, value: ''),
      Cell(x: 9, y: 8, value: '#'),
      Cell(x: 9, y: 9, value: ''),
      Cell(x: 9, y: 10, value: '#'),
      Cell(x: 9, y: 11, value: ''),
      Cell(x: 9, y: 12, value: ''),
      Cell(x: 9, y: 13, value: ''),
      Cell(x: 9, y: 14, value: '#'),
      Cell(x: 9, y: 15, value: ''),
      Cell(x: 9, y: 16, value: '#'),
      Cell(x: 9, y: 17, value: ''),
      Cell(x: 9, y: 18, value: ''),
      Cell(x: 9, y: 19, value: ''),
      Cell(x: 9, y: 20, value: '#'),
    ],
    [
      Cell(x: 10, y: 0, value: '#'),
      Cell(x: 10, y: 1, value: '#'),
      Cell(x: 10, y: 2, value: '#'),
      Cell(x: 10, y: 3, value: ''),
      Cell(x: 10, y: 4, value: '#'),
      Cell(x: 10, y: 5, value: ''),
      Cell(x: 10, y: 6, value: '#'),
      Cell(x: 10, y: 7, value: ''),
      Cell(x: 10, y: 8, value: '#'),
      Cell(x: 10, y: 9, value: '#'),
      Cell(x: 10, y: 10, value: '#'),
      Cell(x: 10, y: 11, value: ''),
      Cell(x: 10, y: 12, value: '#'),
      Cell(x: 10, y: 13, value: '#'),
      Cell(x: 10, y: 14, value: '#'),
      Cell(x: 10, y: 15, value: '#'),
      Cell(x: 10, y: 16, value: '#'),
      Cell(x: 10, y: 17, value: ''),
      Cell(x: 10, y: 18, value: '#'),
      Cell(x: 10, y: 19, value: '#'),
      Cell(x: 10, y: 20, value: '#'),
    ],
    [
      Cell(x: 11, y: 0, value: '#'),
      Cell(x: 11, y: 1, value: ''),
      Cell(x: 11, y: 2, value: ''),
      Cell(x: 11, y: 3, value: ''),
      Cell(x: 11, y: 4, value: '#'),
      Cell(x: 11, y: 5, value: ''),
      Cell(x: 11, y: 6, value: ''),
      Cell(x: 11, y: 7, value: ''),
      Cell(x: 11, y: 8, value: ''),
      Cell(x: 11, y: 9, value: ''),
      Cell(x: 11, y: 10, value: ''),
      Cell(x: 11, y: 11, value: ''),
      Cell(x: 11, y: 12, value: ''),
      Cell(x: 11, y: 13, value: ''),
      Cell(x: 11, y: 14, value: ''),
      Cell(x: 11, y: 15, value: ''),
      Cell(x: 11, y: 16, value: ''),
      Cell(x: 11, y: 17, value: ''),
      Cell(x: 11, y: 18, value: '#'),
      Cell(x: 11, y: 19, value: ''),
      Cell(x: 11, y: 20, value: '#'),
    ],
    [
      Cell(x: 12, y: 0, value: '#'),
      Cell(x: 12, y: 1, value: '#'),
      Cell(x: 12, y: 2, value: '#'),
      Cell(x: 12, y: 3, value: '#'),
      Cell(x: 12, y: 4, value: '#'),
      Cell(x: 12, y: 5, value: ''),
      Cell(x: 12, y: 6, value: '#'),
      Cell(x: 12, y: 7, value: ''),
      Cell(x: 12, y: 8, value: '#'),
      Cell(x: 12, y: 9, value: ''),
      Cell(x: 12, y: 10, value: '#'),
      Cell(x: 12, y: 11, value: ''),
      Cell(x: 12, y: 12, value: '#'),
      Cell(x: 12, y: 13, value: ''),
      Cell(x: 12, y: 14, value: '#'),
      Cell(x: 12, y: 15, value: '#'),
      Cell(x: 12, y: 16, value: '#'),
      Cell(x: 12, y: 17, value: ''),
      Cell(x: 12, y: 18, value: '#'),
      Cell(x: 12, y: 19, value: ''),
      Cell(x: 12, y: 20, value: '#'),
    ],
    [
      Cell(x: 13, y: 0, value: '#'),
      Cell(x: 13, y: 1, value: ''),
      Cell(x: 13, y: 2, value: ''),
      Cell(x: 13, y: 3, value: ''),
      Cell(x: 13, y: 4, value: ''),
      Cell(x: 13, y: 5, value: ''),
      Cell(x: 13, y: 6, value: '#'),
      Cell(x: 13, y: 7, value: ''),
      Cell(x: 13, y: 8, value: '#'),
      Cell(x: 13, y: 9, value: ''),
      Cell(x: 13, y: 10, value: '#'),
      Cell(x: 13, y: 11, value: ''),
      Cell(x: 13, y: 12, value: '#'),
      Cell(x: 13, y: 13, value: ''),
      Cell(x: 13, y: 14, value: '#'),
      Cell(x: 13, y: 15, value: ''),
      Cell(x: 13, y: 16, value: ''),
      Cell(x: 13, y: 17, value: ''),
      Cell(x: 13, y: 18, value: '#'),
      Cell(x: 13, y: 19, value: ''),
      Cell(x: 13, y: 20, value: '#'),
    ],
    [
      Cell(x: 14, y: 0, value: '#'),
      Cell(x: 14, y: 1, value: ''),
      Cell(x: 14, y: 2, value: '#'),
      Cell(x: 14, y: 3, value: ''),
      Cell(x: 14, y: 4, value: '#'),
      Cell(x: 14, y: 5, value: ''),
      Cell(x: 14, y: 6, value: '#'),
      Cell(x: 14, y: 7, value: '#'),
      Cell(x: 14, y: 8, value: '#'),
      Cell(x: 14, y: 9, value: ''),
      Cell(x: 14, y: 10, value: '#'),
      Cell(x: 14, y: 11, value: '#'),
      Cell(x: 14, y: 12, value: '#'),
      Cell(x: 14, y: 13, value: ''),
      Cell(x: 14, y: 14, value: '#'),
      Cell(x: 14, y: 15, value: '#'),
      Cell(x: 14, y: 16, value: '#'),
      Cell(x: 14, y: 17, value: ''),
      Cell(x: 14, y: 18, value: '#'),
      Cell(x: 14, y: 19, value: ''),
      Cell(x: 14, y: 20, value: '#'),
    ],
    [
      Cell(x: 15, y: 0, value: '#'),
      Cell(x: 15, y: 1, value: ''),
      Cell(x: 15, y: 2, value: '#'),
      Cell(x: 15, y: 3, value: ''),
      Cell(x: 15, y: 4, value: '#'),
      Cell(x: 15, y: 5, value: ''),
      Cell(x: 15, y: 6, value: '#'),
      Cell(x: 15, y: 7, value: ''),
      Cell(x: 15, y: 8, value: ''),
      Cell(x: 15, y: 9, value: ''),
      Cell(x: 15, y: 10, value: ''),
      Cell(x: 15, y: 11, value: ''),
      Cell(x: 15, y: 12, value: '#'),
      Cell(x: 15, y: 13, value: ''),
      Cell(x: 15, y: 14, value: '#'),
      Cell(x: 15, y: 15, value: ''),
      Cell(x: 15, y: 16, value: '#'),
      Cell(x: 15, y: 17, value: ''),
      Cell(x: 15, y: 18, value: ''),
      Cell(x: 15, y: 19, value: ''),
      Cell(x: 15, y: 20, value: '#'),
    ],
    [
      Cell(x: 16, y: 0, value: '#'),
      Cell(x: 16, y: 1, value: '#'),
      Cell(x: 16, y: 2, value: '#'),
      Cell(x: 16, y: 3, value: '#'),
      Cell(x: 16, y: 4, value: '#'),
      Cell(x: 16, y: 5, value: '#'),
      Cell(x: 16, y: 6, value: '#'),
      Cell(x: 16, y: 7, value: '#'),
      Cell(x: 16, y: 8, value: '#'),
      Cell(x: 16, y: 9, value: '#'),
      Cell(x: 16, y: 10, value: '#'),
      Cell(x: 16, y: 11, value: ''),
      Cell(x: 16, y: 12, value: '#'),
      Cell(x: 16, y: 13, value: ''),
      Cell(x: 16, y: 14, value: '#'),
      Cell(x: 16, y: 15, value: ''),
      Cell(x: 16, y: 16, value: '#'),
      Cell(x: 16, y: 17, value: ''),
      Cell(x: 16, y: 18, value: '#'),
      Cell(x: 16, y: 19, value: ''),
      Cell(x: 16, y: 20, value: '#'),
    ],
    [
      Cell(x: 17, y: 0, value: '#'),
      Cell(x: 17, y: 1, value: ''),
      Cell(x: 17, y: 2, value: '#'),
      Cell(x: 17, y: 3, value: ''),
      Cell(x: 17, y: 4, value: ''),
      Cell(x: 17, y: 5, value: ''),
      Cell(x: 17, y: 6, value: ''),
      Cell(x: 17, y: 7, value: ''),
      Cell(x: 17, y: 8, value: ''),
      Cell(x: 17, y: 9, value: ''),
      Cell(x: 17, y: 10, value: ''),
      Cell(x: 17, y: 11, value: ''),
      Cell(x: 17, y: 12, value: '#'),
      Cell(x: 17, y: 13, value: ''),
      Cell(x: 17, y: 14, value: ''),
      Cell(x: 17, y: 15, value: ''),
      Cell(x: 17, y: 16, value: '#'),
      Cell(x: 17, y: 17, value: ''),
      Cell(x: 17, y: 18, value: '#'),
      Cell(x: 17, y: 19, value: ''),
      Cell(x: 17, y: 20, value: '#'),
    ],
    [
      Cell(x: 18, y: 0, value: '#'),
      Cell(x: 18, y: 1, value: ''),
      Cell(x: 18, y: 2, value: '#'),
      Cell(x: 18, y: 3, value: '#'),
      Cell(x: 18, y: 4, value: '#'),
      Cell(x: 18, y: 5, value: ''),
      Cell(x: 18, y: 6, value: '#'),
      Cell(x: 18, y: 7, value: '#'),
      Cell(x: 18, y: 8, value: '#'),
      Cell(x: 18, y: 9, value: ''),
      Cell(x: 18, y: 10, value: '#'),
      Cell(x: 18, y: 11, value: ''),
      Cell(x: 18, y: 12, value: '#'),
      Cell(x: 18, y: 13, value: ''),
      Cell(x: 18, y: 14, value: '#'),
      Cell(x: 18, y: 15, value: '#'),
      Cell(x: 18, y: 16, value: '#'),
      Cell(x: 18, y: 17, value: ''),
      Cell(x: 18, y: 18, value: '#'),
      Cell(x: 18, y: 19, value: '#'),
      Cell(x: 18, y: 20, value: '#'),
    ],
    [
      Cell(x: 19, y: 0, value: '#'),
      Cell(x: 19, y: 1, value: ''),
      Cell(x: 19, y: 2, value: ''),
      Cell(x: 19, y: 3, value: ''),
      Cell(x: 19, y: 4, value: ''),
      Cell(x: 19, y: 5, value: ''),
      Cell(x: 19, y: 6, value: ''),
      Cell(x: 19, y: 7, value: ''),
      Cell(x: 19, y: 8, value: '#'),
      Cell(x: 19, y: 9, value: ''),
      Cell(x: 19, y: 10, value: '#'),
      Cell(x: 19, y: 11, value: ''),
      Cell(x: 19, y: 12, value: '#'),
      Cell(x: 19, y: 13, value: ''),
      Cell(x: 19, y: 14, value: '#'),
      Cell(x: 19, y: 15, value: ''),
      Cell(x: 19, y: 16, value: ''),
      Cell(x: 19, y: 17, value: ''),
      Cell(x: 19, y: 18, value: ''),
      Cell(x: 19, y: 19, value: 'G'),
      Cell(x: 19, y: 20, value: '#'),
    ],
    [
      Cell(x: 20, y: 0, value: '#'),
      Cell(x: 20, y: 1, value: '#'),
      Cell(x: 20, y: 2, value: '#'),
      Cell(x: 20, y: 3, value: '#'),
      Cell(x: 20, y: 4, value: '#'),
      Cell(x: 20, y: 5, value: '#'),
      Cell(x: 20, y: 6, value: '#'),
      Cell(x: 20, y: 7, value: '#'),
      Cell(x: 20, y: 8, value: '#'),
      Cell(x: 20, y: 9, value: '#'),
      Cell(x: 20, y: 10, value: '#'),
      Cell(x: 20, y: 11, value: '#'),
      Cell(x: 20, y: 12, value: '#'),
      Cell(x: 20, y: 13, value: '#'),
      Cell(x: 20, y: 14, value: '#'),
      Cell(x: 20, y: 15, value: '#'),
      Cell(x: 20, y: 16, value: '#'),
      Cell(x: 20, y: 17, value: '#'),
      Cell(x: 20, y: 18, value: '#'),
      Cell(x: 20, y: 19, value: '#'),
      Cell(x: 20, y: 20, value: '#'),
    ],
  ];
}
